#!/bin/bash
# 批量修复 Prisma snake_case → camelCase 字段重命名

TARGET_DIR="/workspace/backend/src/modules"
TEST_DIR="/workspace/backend/src/__tests__"
SERVICES_DIR="/workspace/backend/src/services"
GUARDS_DIR="/workspace/backend/src/common/guards"

FILES=$(find "$TARGET_DIR" "$TEST_DIR" "$SERVICES_DIR" "$GUARDS_DIR" -name "*.ts" -type f 2>/dev/null)

# 字段重命名（长的在前，避免前缀匹配）
FIELDS=(
  "student_no:studentNo"
  "teacher_no:teacherNo"
  "leave_no:leaveNo"
  "notice_no:noticeNo"
  "task_no:taskNo"
  "room_no:roomNo"
  "bed_no:bedNo"
  "head_teacher_id:headTeacherId"
  "director_teacher_id:directorId"
  "vice_head_teacher_id:viceHeadTeacherId"
  "student_name:studentName"
  "teacher_name:teacherName"
  "applicant_id:applicantId"
  "applicant_name:applicantName"
  "approver_id:approverId"
  "approver_name:approverName"
  "approve_remark:approveRemark"
  "reject_reason:rejectReason"
  "cancel_reason:cancelReason"
  "leave_type:leaveType"
  "leave_reason_type:leaveReasonType"
  "boarding_type:boardingType"
  "current_count:currentCount"
  "current_status:currentStatus"
  "current_location:currentLocation"
  "status_updated_at:statusUpdatedAt"
  "location_updated_at:locationUpdatedAt"
  "start_date:startDate"
  "end_date:endDate"
  "start_at:startAt"
  "end_at:endAt"
  "actual_left_at:actualLeftAt"
  "actual_returned_at:actualReturnedAt"
  "expected_return_time:expectedReturnTime"
  "expected_return_note:expectedReturnNote"
  "approved_at:approvedAt"
  "rejected_at:rejectedAt"
  "closed_at:closedAt"
  "published_at:publishedAt"
  "archived_at:archivedAt"
  "confirm_at:confirmAt"
  "confirm_deadline:confirmDeadline"
  "read_at:readAt"
  "is_read:isRead"
  "require_confirm:requireConfirm"
  "content_format:contentFormat"
  "notice_type:noticeType"
  "publisher_id:publisherId"
  "publisher_name:publisherName"
  "teaching_group:teachingGroup"
  "permission_code:permissionCode"
  "permission_name:permissionName"
  "permission_id:permissionId"
  "role_code:roleCode"
  "role_name:roleName"
  "role_id:roleId"
  "created_at:createdAt"
  "updated_at:updatedAt"
  "deleted_at:deletedAt"
  "class_id:classId"
  "grade_id:gradeId"
  "school_id:schoolId"
  "student_id:studentId"
  "teacher_id:teacherId"
  "building_id:buildingId"
  "dorm_id:dormId"
  "parent_id:parentId"
  "user_id:userId"
  "source_id:sourceEventId"
  "event_type:eventType"
  "event_source:eventSource"
  "operator_id:operatorId"
  "operator_name:operatorName"
  "operator_role:operatorRole"
  "occurred_at:occurredAt"
  "recorded_at:recordedAt"
  "related_type:relatedType"
  "related_id:relatedId"
  "leave_record_id:leaveRecordId"
  "notice_id:noticeId"
  "is_system:isSystem"
  "attachment_ids:attachmentIds"
  "return_judgment:returnJudgment"
  "due_at:dueAt"
  "completed_at:completedAt"
  "completion_remark:completionRemark"
  "reminder_count:reminderCount"
  "last_reminded_at:lastRemindedAt"
  "assignee_id:assigneeId"
  "assignee_name:assigneeName"
  "creator_id:creatorId"
  "creator_name:creatorName"
  "short_name:shortName"
  "principal_name:principalName"
  "contact_phone:contactPhone"
  "enrollment_year:enrollmentYear"
  "graduation_year:graduationYear"
  "student_count:studentCount"
  "manager_id:managerId"
  "wechat_openid:wechatOpenid"
  "wechat_unionid:wechatUnionid"
  "notify_preference:notifyPreference"
  "is_primary:isPrimary"
  "password_hash:passwordHash"
  "user_type:userType"
  "last_login_at:lastLoginAt"
  "last_login_ip:lastLoginIp"
  "external_id:externalId"
  "credential_hash:credentialHash"
  "verified_at:verifiedAt"
  "enrolled_at:enrolledAt"
  "graduated_at:graduatedAt"
  "transferred_at:transferredAt"
)

for pair in "${FIELDS[@]}"; do
  snake="${pair%%:*}"
  camel="${pair##*:}"
  for file in $FILES; do
    sed -i "s/\b${snake}\b/${camel}/g" "$file"
  done
done

# Prisma Client 模型名修正
for file in $FILES; do
  sed -i 's/prisma\.timeline\./prisma.timelineEvent./g' "$file"
  sed -i 's/prisma\.todo\./prisma.task./g' "$file"
  sed -i 's/tx\.timeline\./tx.timelineEvent./g' "$file"
  sed -i 's/tx\.todo\./tx.task./g' "$file"
done

# 模块路径修正
for file in $(find "$TARGET_DIR" -path "*/capability-service.ts" -type f); do
  sed -i "s|from '../authorization/types'|from '../../authorization/types'|g" "$file"
done

echo "批量重命名完成"
